name: Flutter CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'lib/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Debug)
        run: flutter build apk --debug
