name: Flutter CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'Codigo/lib/**'
      - 'Codigo/test/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'

      - name: Install dependencies
        run: flutter pub get
        working-directory: Codigo
        
      - name: Generate Mocks
        run: flutter pub run build_runner build --delete-conflicting-outputs
        working-directory: Codigo
        
      - name: Run Tests
        run: flutter test
        working-directory: Codigo

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'

      - name: Install dependencies
        run: flutter pub get
        working-directory: Codigo

      - name: Create key.properties
        run: |
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" > Codigo/android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> Codigo/android/key.properties
          echo "storeFile=upload-keystore.jks" >> Codigo/android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> Codigo/android/key.properties

      - name: Decode and place keystore.jks
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > Codigo/android/app/upload-keystore.jks

      - name: Build APK (Debug)
        run: flutter build apk --debug
        working-directory: Codigo
